// Package appcli gives plasma-settings-migrator the command line options every released tool
// wants: --help, --version, --install and --upgrade. It was generated by
// goscaffold and is yours to edit; main only has to hand it the arguments:
//
//	if handled, code := appcli.Handle(os.Args[1:]); handled {
//		os.Exit(code)
//	}
package appcli

// AppName is the name of the program's binary, without any ".exe". It is
// also what release zips are named after (plasma-settings-migrator-linux-amd64.zip and so on).
const AppName = "plasma-settings-migrator"

// Releases is the GitHub releases page --upgrade downloads from. A variable
// so tests can point it at a stand-in server.
var Releases = "https://github.com/fluffynuts/plasma-settings-migrator/releases"

// Usage is the usage line --help shows. A program that takes arguments
// beyond options can say so here: AppName + " [options] <path>".
var Usage = AppName + " [options]"

// ExtraHelp is shown in --help after the options built in here, so the
// program's own options can be documented in the same place. Lay them out
// like the built-in ones: two spaces, the option, then what it does.
var ExtraHelp = ""

// Examples are the usage examples --help ends with, one command per line.
var Examples = []string{
	AppName + " --version",
	AppName + " --install",
	AppName + " --upgrade",
}
